"""Driver — what scenario tests use to "drive" the application the way a person does.

Unlike the other page objects, which READ the screen, this one ACTS on it — it fills
a form by its labels, clicks a row-menu item, confirms a dialog. Scenario tests check
chains of rules, and those fire only on this path: calling a CRUD method directly,
bypassing the form, does not trigger them, and the test then proves the wrong thing.

Fields are located by their visible label, not by id: ids are generated by the
platform and change from one import to the next, while labels are set by the project
and survive a rebuild.
"""
from __future__ import annotations

import os

from helpers.env import CONFIG

SHOT = "test-results/screenshots"


class Driver:
    """Thin wrapper: open a page, fill a form by its labels, click a row action."""

    def __init__(self, page):
        self.page = page

    # ---------- navigation ----------
    def open(self, path: str, settle: int = 3000, tries: int = 3):
        """Open a project page.

        ⛔ `goto` can be interrupted by a re-render or a redirect of the previous page —
        `net::ERR_ABORTED`. That is a navigation race, not an application failure, yet
        the message reads as "the page did not open" and blames the product. So retry.
        """
        last = None
        for attempt in range(tries):
            try:
                self.page.goto(CONFIG.url(path), wait_until="domcontentloaded")
                self.page.wait_for_timeout(settle)
                return self
            except Exception as exc:  # noqa: BLE001 — all that matters is whether it is a navigation error
                last = exc
                if "ERR_ABORTED" not in str(exc) and "interrupted" not in str(exc).lower():
                    raise
                self.page.wait_for_timeout(1500)
        raise AssertionError(
            f"page /{path} did not open in {tries} attempts: {last}"
        )

    def shot(self, name: str):
        os.makedirs(SHOT, exist_ok=True)
        self.page.screenshot(path=os.path.join(SHOT, f"{name}.png"), full_page=True)

    # ---------- forms ----------
    def fields(self):
        return self.page.evaluate(r"""() => {
          const vis=e=>e.offsetParent!==null;
          // ⛔ Labels are compared CASE-INSENSITIVELY and without a trailing ":"/"*": the
          // theme prints some labels in capitals (`text-transform`), and the project writes
          // "Order date" where the control's name is "Order Date". An exact comparison
          // declared the field missing, although it was on the form with the same label.
          const norm=t=>(t||'').replace(/[\s:*]+$/,'').trim().toLowerCase();
          const lbl=e=>{let p=e,l='';for(let k=0;k<6&&p;k++){p=p.parentElement;if(!p)break;
            const q=p.querySelector('label'); if(q){l=q.innerText.trim();break;}} return l;};
          return [...document.querySelectorAll('input,select,textarea')].filter(vis)
            .map(e=>({tag:e.tagName, type:e.type||'', label:lbl(e),
                      value:(e.value||'').slice(0,40),
                      // ⛔ "no such field" and "read-only field" are different things: the
                      // platform renders a prohibited control as an ordinary <input>, so
                      // editability shows only in these two flags, not in whether the tag exists.
                      disabled:!!e.disabled, readonly:!!e.readOnly,
                      options:e.tagName==='SELECT'?[...e.options].slice(0,60).map(o=>o.text.trim()):null}));
        }""")

    def fill(self, pairs):
        """pairs: [(tag, label, value)] — a SELECT option is matched exactly, then by prefix, then by substring.

        `label` is a label OR a list of candidate labels: labels depend on the session
        language, and the test must not need to know which language the page is in.

        Returns {label: result}, keyed by the first candidate label. The result is the
        value the field holds after writing (for SELECT, the chosen option's text), or
        one of two sentinels to assert on:
          'NOT FOUND'          — no visible field has that label;
          'NO OPTION ' + value — the SELECT has no option matching the value.
        """
        return self.page.evaluate(r"""(pairs) => {
          const vis=e=>e.offsetParent!==null;
          const fire=e=>['input','change'].forEach(n=>e.dispatchEvent(new Event(n,{bubbles:true})));
          // ⛔ Labels are compared CASE-INSENSITIVELY and without a trailing ":"/"*": the
          // theme prints some labels in capitals (`text-transform`), and the project writes
          // "Order date" where the control's name is "Order Date". An exact comparison
          // declared the field missing, although it was on the form with the same label.
          const norm=t=>(t||'').replace(/[\s:*]+$/,'').trim().toLowerCase();
          const lbl=e=>{let p=e,l='';for(let k=0;k<6&&p;k++){p=p.parentElement;if(!p)break;
            const q=p.querySelector('label'); if(q){l=q.innerText.trim();break;}} return l;};

          // ⛔ `<input type=number>` SILENTLY drops a value it cannot parse:
          // `el.value = '33,5'` in an English session leaves the field EMPTY, and the
          // test carries on with an empty value. So after writing, check that the value
          // stuck, and try the other decimal separator.
          const setVal=(el,v)=>{
            el.value=v; fire(el);
            if((el.value||'')==='' && v!==''){
              const alt = v.includes(',') ? v.replace(',','.') : v.replace('.',',');
              if(alt!==v){ el.value=alt; fire(el); }
            }
            return el.value;
          };
          const all=[...document.querySelectorAll('input,select,textarea')].filter(vis);
          const out={};
          for (const [tag,labels,val] of pairs) {
            const want=Array.isArray(labels)?labels:[labels];
            const label=want[0];
            const tags = tag==='INPUT' ? ['INPUT','TEXTAREA']
                       : (tag==='TEXTAREA' ? ['TEXTAREA','INPUT'] : [tag]);
            let el=null;
            for (const w of want) {
              for (const tg of tags) {
                const els=all.filter(e=>e.tagName===tg && norm(lbl(e))===norm(w));
                if(els.length){ el=els[els.length-1]; break; }
              }
              if(el) break;
            }
            if(!el){ out[label]='NOT FOUND'; continue; }
            if(tag==='SELECT'){
              const o=[...el.options].find(x=>x.text.trim()===val)
                   || [...el.options].find(x=>x.text.trim().startsWith(val))
                   || [...el.options].find(x=>x.text.trim().includes(val));
              if(!o){ out[label]='NO OPTION '+val; continue; }
              el.value=o.value; fire(el); out[label]=o.text.trim();
            } else { out[label]=setVal(el,val); }
          }
          return out;
        }""", pairs)

    def click_text(self, text: str, last: bool = True, tries: int = 5):
        """Click a button by its visible caption, after waiting for it to appear.

        ⛔ One attempt is not enough: filling a field sends an AJAX request to Wicket, which
        re-renders the panel, and the button vanishes from the DOM for a fraction of a
        second. Because of that, the first run of a scenario concluded that there was no
        "Add row" button at all — although there was.
        """
        for _ in range(tries):
            r = self.page.evaluate("""([t,last]) => {
                 const els=[...document.querySelectorAll('a,button')].filter(e=>e.offsetParent && e.innerText.trim()===t);
                 if(!els.length) return false;
                 (last? els[els.length-1] : els[0]).click(); return true;
               }""", [text, last])
            if r:
                self.page.wait_for_timeout(3500)
                return True
            self.page.wait_for_timeout(1500)
        return False

    def modal_press(self, text: str, first: bool = True, tries: int = 4) -> bool:
        """Click a button INSIDE the open dialog — by default the FIRST of the matches.

        ⛔ On an action form, the caption of the confirm button can be the same as that
        of the close button ("Close" on a "Close order" action). `click_text` takes the
        LAST one — that is, it closes the dialog instead of submitting the form, and the
        test reports "the order was not closed". Inside the dialog the submit button
        comes first.
        """
        for _ in range(tries):
            r = self.page.evaluate("""([t, first]) => {
                 const dlgs=[...document.querySelectorAll('.modal-content,[role=dialog],.modal-dialog')]
                            .filter(e=>e.offsetParent!==null);
                 const dlg=dlgs[dlgs.length-1];
                 if(!dlg) return false;
                 const els=[...dlg.querySelectorAll('a,button')]
                           .filter(e=>e.offsetParent!==null && e.innerText.trim()===t);
                 if(!els.length) return false;
                 (first? els[0] : els[els.length-1]).click(); return true;
               }""", [text, first])
            if r:
                self.page.wait_for_timeout(3500)
                return True
            self.page.wait_for_timeout(1200)
        return False

    def press_filled(self, text: str, tries: int = 4) -> bool:
        """Click a button in the dialog that the last `modal_fill` filled in.

        ⛔ Neither "the last button with this caption on the page" nor "the last dialog
        in the DOM" will do: closed dialogs from previous steps stay in the markup and
        are visible to the browser. The click silently went into them — and a scenario
        "created" an order that never appeared in the database.
        """
        for _ in range(tries):
            r = self.page.evaluate("""(t) => {
                 const dlg=document.querySelector('[data-at-filled]');
                 const scope=dlg && dlg.offsetParent!==null ? dlg : null;
                 if(!scope) return false;
                 const els=[...scope.querySelectorAll('a,button')]
                           .filter(e=>e.offsetParent!==null && e.innerText.trim()===t);
                 if(!els.length) return false;
                 els[0].click(); return true;
               }""", text)
            if r:
                self.page.wait_for_timeout(3500)
                return True
            self.page.wait_for_timeout(1200)
        return False

    def confirm(self, settle: int = 4000):
        """Confirm a dialog. `settle` is how long to wait after the click.

        ⛔ A short `settle` is needed where a REJECTION is checked: the platform's
        message lives for seconds, and by the end of the regular wait it is already gone
        from the page — the test then reports "the rejection did not name the parameter"
        about a correct rejection.
        """
        # Да / Yes / Այո: the platform's own "Yes" caption in Russian, English and Armenian.
        r = self.page.evaluate("""() => {
             const b=[...document.querySelectorAll('a,button')].filter(e=>e.offsetParent && /^(Да|Yes|Այո)$/.test(e.innerText.trim()));
             if(!b.length) return false; b[0].click(); return true;
           }""")
        self.page.wait_for_timeout(settle)
        return r

    def wait_toast(self, pattern: str, timeout_ms: int = 12000, body: bool = True) -> str:
        """Wait for a platform message and return it whole ('' — none came).

        A rejection message arrives asynchronously (Wicket finishes rendering the panel)
        and disappears by itself. So it is POLLED, not read once: "read it six seconds
        later and did not find it" is about timing, not about the product.
        """
        import re as _re
        rx = _re.compile(pattern, _re.I)
        waited = 0
        while waited < timeout_ms:
            for t in self.toasts():
                if rx.search(t):
                    return t
            # ⛔ The text of the WHOLE page is the last resort, and only for a narrow pattern:
            # a broad one (`.{8,}`) matches the navigation, and the test "reads the rejection"
            # in the site menu. One run reported exactly that: "the rejection did not name
            # the amount", quoting "site · change theme · orders …" instead of the message.
            if body:
                text = self.page.evaluate("() => document.body.innerText") or ""
                m = rx.search(text)
                if m:
                    i = max(0, m.start() - 160)
                    return text[i:m.end() + 160].replace("\n", " ")
            self.page.wait_for_timeout(500)
            waited += 500
        return ""

    def wait_modal(self, timeout_ms: int = 9000) -> bool:
        """Wait for a modal dialog. True — it appeared.

        ⛔ The dialog arrives via AJAX and on a live server takes 3–6 seconds to open. A
        check that looked right after the click declared "the form does not open in this
        build" and skipped itself — with hundreds of records in the database and a
        working form.
        """
        waited = 0
        while waited < timeout_ms:
            if self.modal_open():
                return True
            self.page.wait_for_timeout(500)
            waited += 500
        return False

    def modal_open(self) -> int:
        """How many modal dialogs are open RIGHT NOW (0 — none)."""
        return self.page.evaluate("""() => [...document.querySelectorAll('.modal-content,[role=dialog],.modal-dialog')]
                                          .filter(e=>e.offsetParent!==null).length""")

    def modal_errors(self):
        """The rejection text the form printed INSIDE ITSELF.

        ⛔ A form can reject SILENTLY as far as everything outside it is concerned: no
        toast, the button clicks, the dialog stays open, and the test's next step
        navigates away and takes the message with it. That is how an e-mail validator's
        rejection went unnoticed, and how an order was repeatedly "created" that then
        was not in the database — while the test carried on with an UNRELATED order and
        blamed the product for a wrong calculation.

        So after every save, the message is read from the dialog ITSELF.
        """
        return self.page.evaluate(r"""() => {
          const mk=document.querySelector('[data-at-filled]');
          const dlg=(mk && mk.offsetParent!==null) ? mk
                  : [...document.querySelectorAll('.modal-content,[role=dialog],.modal-dialog')]
                    .filter(e=>e.offsetParent!==null).pop();
          if(!dlg) return [];
          const sel='.invalid-feedback,.text-danger,.has-error,.feedbackPanel,.feedbackPanelERROR,'
                   +'.alert,.error,.errorMessage,[class*=feedbackPanel]';
          const out=[];
          for (const e of dlg.querySelectorAll(sel)) {
            if(e.offsetParent===null) continue;
            const t=(e.innerText||'').trim();
            if(t && t.length<=300 && !out.includes(t)) out.push(t);
          }
          return out;
        }""")

    # ---------- table ----------
    def rows(self):
        return self.page.evaluate("""() => {
          const ts=[...document.querySelectorAll('table')].sort((a,b)=>b.innerText.length-a.innerText.length);
          if(!ts.length) return [];
          return [...ts[0].querySelectorAll('tbody tr')].map(tr=>[...tr.querySelectorAll('td')].map(td=>td.innerText.trim()));
        }""")

    def modal_rows(self):
        """Rows of the table INSIDE the open modal dialog.

        ⛔ The plain `rows()` takes the biggest table on the page — and under an open form
        lies the register, which is almost always bigger than the line-items grid. Because
        of that, the first run of a scenario reported "line rows: 0", although the
        database had several.
        """
        return self.page.evaluate("""() => {
          const dlg=[...document.querySelectorAll('.modal-content,[role=dialog],.modal-dialog')]
                    .filter(e=>e.offsetParent!==null).pop();
          if(!dlg) return null;
          const t=[...dlg.querySelectorAll('table')].sort((a,b)=>b.innerText.length-a.innerText.length)[0];
          if(!t) return [];
          return [...t.querySelectorAll('tbody tr')].map(tr=>[...tr.querySelectorAll('td')].map(td=>td.innerText.trim()));
        }""")

    def modal_rows_wait(self, min_rows: int, timeout_ms: int = 12000):
        """Rows of the table in the dialog, but WAITING for the required count.

        ⛔ The LINE form replaces the content of the same dialog, and the return to the
        document form arrives via AJAX in 3–5 seconds. The document grid read right away
        is empty — and that looks like "the document's lines get lost", i.e. like a defect
        that once really existed. "Not back yet" can be told from "lost" only by waiting,
        so the row count is WAITED for.
        """
        rows, waited = [], 0
        while waited < timeout_ms:
            rows = self.modal_rows() or []
            if len(rows) >= min_rows:
                return rows
            self.page.wait_for_timeout(700)
            waited += 700
        return rows

    def tab(self, caption: str):
        """Open a page tab by its caption — and wait for the re-render.

        ⛔ A tab is the USER's state on the server, not the browser's: selected in one
        test, it stays selected in all the following ones. On an orders page this fed the
        test the INVOICES register instead of the orders ("no column TOTAL"), and on
        another page the form of a DIFFERENT tab instead of the one under test. The
        required tab is selected explicitly, every time.
        """
        ok = self.page.evaluate("""(cap) => {
             const els=[...document.querySelectorAll('a,button,li')].filter(e=>e.offsetParent!==null);
             const el=els.find(e=>(e.innerText||'').trim()===cap &&
                                  /nav-link|tab/.test((e.className||'')+''));
             if(!el) return false;
             el.click(); return true;
           }""", caption)
        if not ok:
            # fallback: any VISIBLE element with this caption (a tab can be rendered
            # without the nav-link class)
            ok = self.page.evaluate("""(cap) => {
                 const el=[...document.querySelectorAll('a,button,li,span')]
                          .filter(e=>e.offsetParent!==null)
                          .find(e=>(e.innerText||'').trim()===cap);
                 if(!el) return false;
                 el.click(); return true;
               }""", caption)
        self.page.wait_for_timeout(3000)
        return bool(ok)

    def grid(self, *headers):
        """The table whose header HAS the given columns — with its whole header and rows.

        ⛔ "The biggest table on the page" is not always the right one. On an orders page
        an invoices register sits next to the orders one (many times more rows), and
        `rows()` returned IT: the test reported "the orders register has no TOTAL column",
        listing the invoice columns. A table is chosen by what must be in it.

        Returns {'head': [...], 'rows': [[...]]}; empty lists if there is no such table.
        """
        want = [h.upper() for h in headers]
        return self.page.evaluate("""(want) => {
          const val=td=>{
            const t=td.innerText.trim();
            if(t) return t;
            const i=td.querySelector('input,select,textarea');
            return i ? (i.value||'').trim() : '';
          };
          for (const t of [...document.querySelectorAll('table')]) {
            if(t.offsetParent===null) continue;
            const head=[...t.querySelectorAll('thead th, thead td')].map(h=>h.innerText.trim());
            const up=head.map(h=>h.toUpperCase());
            if(!want.every(w=>up.some(h=>h===w || h.includes(w)))) continue;
            return {head: head,
                    rows: [...t.querySelectorAll('tbody tr')].map(tr=>[...tr.querySelectorAll('td')].map(val))};
          }
          return {head: [], rows: []};
        }""", want)

    def modal_grid(self):
        """Header AND rows of the table inside the open modal dialog.

        ⛔ The numeric cell you need must NOT be found by scanning for "the first number
        in the row". An item code itself looks like a number: in `ITEM-003` a number
        regex sees `-003`, and a quantity check declared a planned quantity of −3.0 while
        the database held the correct 3.25 — a failure that looked like a product bug.
        So the column is chosen by its header caption, not by position and not "by eye".

        Returns {'head': [captions], 'rows': [[cells]]} — for grids that render the value
        in an `<input>`, the field's value is taken, not the empty innerText.
        """
        return self.page.evaluate("""() => {
          const dlg=[...document.querySelectorAll('.modal-content,[role=dialog],.modal-dialog')]
                    .filter(e=>e.offsetParent!==null).pop();
          if(!dlg) return null;
          const t=[...dlg.querySelectorAll('table')].sort((a,b)=>b.innerText.length-a.innerText.length)[0];
          if(!t) return {head:[], rows:[]};
          const val=td=>{
            const txt=td.innerText.trim();
            if(txt) return txt;
            const inp=td.querySelector('input,select,textarea');
            return inp ? (inp.value||'').trim() : '';
          };
          return {
            head: [...t.querySelectorAll('thead th, thead td')].map(h=>h.innerText.trim()),
            rows: [...t.querySelectorAll('tbody tr')].map(tr=>[...tr.querySelectorAll('td')].map(val))
          };
        }""")

    def row_action(self, row_text: str, action: str):
        """Open the menu of the row that contains row_text and click the item action.

        Returns 'ok', or the reason it could not.
        """
        r = self.page.evaluate("""([rt, act]) => {
             const ts=[...document.querySelectorAll('table')].sort((a,b)=>b.innerText.length-a.innerText.length);
             if(!ts.length) return 'no table';
             const tr=[...ts[0].querySelectorAll('tbody tr')].find(x=>x.innerText.includes(rt));
             if(!tr) return 'no row '+rt;
             const menu=tr.querySelector('td .dropdown-menu');
             if(!menu) return 'no menu';
             const items=[...menu.querySelectorAll('a')];
             const it=items.find(a=>a.innerText.trim()===act);
             if(!it) return 'no item; there are: '+items.map(a=>a.innerText.trim()).join('|');
             it.click(); return 'ok';
           }""", [row_text, action])
        self.page.wait_for_timeout(3500)
        return r

    # ⛔ The feedback panel is ALWAYS present in the DOM — with the headings "Please fix the
    # following errors:", "Warnings:" and an empty list under them. Collect its text without
    # looking at visibility and at whether it has any items, and every successful step looks
    # like a rejection: on the very first run of a scenario, a created order was declared
    # unsaved although it was in the register. Hence: only what is visible, without the
    # service headings and empty wrappers.
    BOILERPLATE = ("please fix the following errors", "field validation errors",
                   "warnings:", "field warnings:", "ignore warnings")

    def row_actions(self, row_text: str, tries: int = 4) -> list[str]:
        """The items of a row's menu — so the test does not guess what an action is called.

        ⛔ An EMPTY menu is not the same as "no actions": Wicket finishes rendering the row
        markup after the table, and a menu read right after `wait_for_rows` came back
        empty for a row that does have actions. The test then reported "the order has no
        'Approve' action" — that is, it blamed the product for a missing button. So an
        empty answer is ASKED AGAIN.
        """
        for _ in range(tries):
            got = self._row_actions_once(row_text)
            if got:
                return got
            self.page.wait_for_timeout(1500)
        return []

    def _row_actions_once(self, row_text: str) -> list[str]:
        return self.page.evaluate("""(rt) => {
             const ts=[...document.querySelectorAll('table')].sort((a,b)=>b.innerText.length-a.innerText.length);
             if(!ts.length) return [];
             const tr=[...ts[0].querySelectorAll('tbody tr')].find(x=>x.innerText.includes(rt));
             if(!tr) return [];
             const menu=tr.querySelector('td .dropdown-menu');
             return menu ? [...menu.querySelectorAll('a')].map(a=>a.innerText.trim()) : [];
           }""", row_text)

    def toasts(self):
        raw = self.page.evaluate("""() => [...document.querySelectorAll(
            "[class*='toast'],[class*='feedback'],[class*='alert'],[role='alert']")]
            .filter(e => e.offsetParent !== null)
            .map(e => e.innerText.trim()).filter(t => t && t !== '×')""")
        out = []
        for t in raw:
            body = "\n".join(l for l in t.splitlines()
                             if l.strip() and not any(b in l.strip().lower() for b in self.BOILERPLATE))
            if body.strip():
                out.append(body.strip())
        return out

    # ---------- what live scenario runs turned out to need ----------

    def modal_fill(self, pairs):
        """Same as `fill`, but ONLY inside the open modal dialog.

        ⛔ Field labels in a line form and in the register's filter are the same ("Item",
        "Quantity", "Unit of measure"), and the register lies under the modal and stays in
        the DOM. `fill` takes the last match on the whole page and on a live run landed
        now in the form, now in the filter — depending on what was rendered last. Here
        the search scope is narrowed to the dialog.

        Returns the same {label: result} map as `fill`, with the same two sentinels to
        assert on: 'NOT FOUND' (no visible field with that label in the dialog) and
        'NO OPTION ' + value (the SELECT has no option matching the value). With no
        dialog open at all it returns {'__': 'NO DIALOG'} ("no modal dialog")
        instead. The filled dialog is marked, so `press_filled` and `modal_errors` act
        on that dialog.
        """
        # ⛔ The modal appears via AJAX, not instantly: on a live run the form had not been
        # rendered yet, the fill silently went into 'NO DIALOG',
        # and the test failed at the next step — "no add-row button", which reads as a
        # product defect. So WAIT for the dialog.
        for _ in range(10):
            if self.page.evaluate("""() => !![...document.querySelectorAll('.modal-content,[role=dialog],.modal-dialog')]
                                          .filter(e=>e.offsetParent!==null).length"""):
                break
            self.page.wait_for_timeout(1000)
        return self.page.evaluate(r"""(pairs) => {
          const dlg=[...document.querySelectorAll('.modal-content,[role=dialog],.modal-dialog')]
                    .filter(e=>e.offsetParent!==null).pop();
          if(!dlg) return {'__': 'NO DIALOG'};
          // ⛔ Mark EXACTLY THIS dialog: the save button is later looked up in it, not as
          // "the last one on the page" and not "in the last dialog in the DOM". Closed
          // dialogs from previous steps stay in the DOM and are still visible to the
          // browser, and the click went into them — the form was not submitted, the test
          // took the record as created and carried on with an UNRELATED record.
          document.querySelectorAll('[data-at-filled]').forEach(e=>e.removeAttribute('data-at-filled'));
          dlg.setAttribute('data-at-filled','1');
          const vis=e=>e.offsetParent!==null;
          const fire=e=>['input','change'].forEach(n=>e.dispatchEvent(new Event(n,{bubbles:true})));
          // ⛔ Labels are compared CASE-INSENSITIVELY and without a trailing ":"/"*": the
          // theme prints some labels in capitals (`text-transform`), and the project writes
          // "Order date" where the control's name is "Order Date". An exact comparison
          // declared the field missing, although it was on the form with the same label.
          const norm=t=>(t||'').replace(/[\s:*]+$/,'').trim().toLowerCase();
          const lbl=e=>{let p=e,l='';for(let k=0;k<6&&p;k++){p=p.parentElement;if(!p)break;
            const q=p.querySelector('label'); if(q){l=q.innerText.trim();break;}} return l;};

          // ⛔ `<input type=number>` SILENTLY drops a value it cannot parse:
          // `el.value = '33,5'` in an English session leaves the field EMPTY, and the
          // test carries on with an empty value. So after writing, check that the value
          // stuck, and try the other decimal separator.
          const setVal=(el,v)=>{
            el.value=v; fire(el);
            if((el.value||'')==='' && v!==''){
              const alt = v.includes(',') ? v.replace(',','.') : v.replace('.',',');
              if(alt!==v){ el.value=alt; fire(el); }
            }
            return el.value;
          };
          const all=[...dlg.querySelectorAll('input,select,textarea')].filter(vis);
          const out={};
          for (const [tag,labels,val] of pairs) {
            const want=Array.isArray(labels)?labels:[labels];
            // ⛔ The tag may not be the one the test expects: "Description" is a textarea,
            // not an input, while the label is the same. This used to read as "no such
            // field", and the test blamed the form for lacking a field that is on it.
            const tags = tag==='INPUT' ? ['INPUT','TEXTAREA']
                       : (tag==='TEXTAREA' ? ['TEXTAREA','INPUT'] : [tag]);
            let el=null, used=null;
            for (const w of want) {
              for (const tg of tags) {
                const els=all.filter(e=>e.tagName===tg && norm(lbl(e))===norm(w));
                if(els.length){ el=els[els.length-1]; used=w; break; }
              }
              if(el) break;
            }
            const key=want[0];
            if(!el){ out[key]='NOT FOUND'; continue; }
            if(tag==='SELECT'){
              const o=[...el.options].find(x=>x.text.trim()===val)
                   || [...el.options].find(x=>x.text.trim().startsWith(val))
                   || [...el.options].find(x=>x.text.trim().includes(val));
              if(!o){ out[key]='NO OPTION '+val; continue; }
              el.value=o.value; fire(el); out[key]=o.text.trim();
            } else { out[key]=setVal(el,val); }
          }
          return out;
        }""", [[t, (l if isinstance(l, list) else [l]), v] for t, l, v in pairs])

    def modal_row_action(self, index: int, action: str):
        """A row-menu item INSIDE the modal dialog — by row NUMBER.

        Rows of nested tables (line items, child records) have no unique text to find
        them by, so this takes an index, not a substring. Returns 'ok' or the reason.
        """
        return self.page.evaluate("""([i, act]) => {
             const dlg=[...document.querySelectorAll('.modal-content,[role=dialog],.modal-dialog')]
                       .filter(e=>e.offsetParent!==null).pop();
             if(!dlg) return 'no dialog';
             const t=[...dlg.querySelectorAll('table')].sort((a,b)=>b.innerText.length-a.innerText.length)[0];
             if(!t) return 'no table in the dialog';
             const tr=[...t.querySelectorAll('tbody tr')][i];
             if(!tr) return 'no row '+i;
             const items=[...tr.querySelector('td').querySelectorAll('a')];
             const it=items.find(a=>a.innerText.trim()===act);
             if(!it) return 'no item; there are: '+items.map(a=>a.innerText.trim()).join('|');
             it.click(); return 'ok';
           }""", [index, action])

    def row_action_at(self, index: int, actions):
        """A row-menu item by row NUMBER — the first match from a list of captions.

        ⛔ Needed where a row has no unique text (line items, log entries): such a row
        cannot be found by substring. And ⛔ the menu is taken FROM THE ROW'S MARKUP, not
        as "the last button in the first cell": the cell also holds invisible items of
        neighbouring menus, and a click on them waits thirty seconds and fails on a
        timeout.

        Returns (clicked_caption, result): 'ok' or the reason. A reason that starts with
        'no row' means the index is past the last row.
        """
        want = actions if isinstance(actions, list) else [actions]
        res = self.page.evaluate("""([i, want]) => {
             const ts=[...document.querySelectorAll('table')]
                      .filter(t=>t.offsetParent!==null)
                      .sort((a,b)=>b.innerText.length-a.innerText.length);
             if(!ts.length) return ['', 'no table'];
             const tr=[...ts[0].querySelectorAll('tbody tr')][i];
             if(!tr) return ['', 'no row '+i];
             const menu=tr.querySelector('td .dropdown-menu');
             if(!menu) return ['', 'no menu on row '+i];
             const items=[...menu.querySelectorAll('a')];
             for (const w of want) {
               const it=items.find(a=>a.innerText.trim()===w);
               if(it){ it.click(); return [w, 'ok']; }
             }
             return ['', 'none of the items; there are: '+items.map(a=>a.innerText.trim()).join('|')];
           }""", [index, want])
        self.page.wait_for_timeout(3000)
        return tuple(res)

    def modal_row_action_any(self, index: int, actions):
        """The same for a row INSIDE the dialog: the first matching item, by row number."""
        want = actions if isinstance(actions, list) else [actions]
        for a in want:
            r = self.modal_row_action(index, a)
            if r == "ok":
                return a, "ok"
        return None, f"none of {want}"

    def row_action_any(self, row_text: str, actions):
        """The first matching item of a row's menu — the caption depends on the locale.

        Returns (clicked_item_name, result). The scenario cares about the action, not
        about what it is called in the current language.
        """
        have = self.row_actions(row_text)
        for a in actions:
            if a in have:
                return a, self.row_action(row_text, a)
        return None, f"none of {actions}; available: {have}"

    def cell(self, row_text: str, header, default: str = "") -> str:
        """A row's cell value by column CAPTION — column positions change."""
        want = header if isinstance(header, list) else [header]
        return self.page.evaluate("""([rt, want, dflt]) => {
             const ts=[...document.querySelectorAll('table')].sort((a,b)=>b.innerText.length-a.innerText.length);
             if(!ts.length) return dflt;
             const t=ts[0];
             const heads=[...t.querySelectorAll('thead th, thead td')].map(h=>h.innerText.trim());
             let idx=-1;
             for (const w of want) { idx=heads.findIndex(h=>h.toLowerCase()===w.toLowerCase()); if(idx>=0) break; }
             if(idx<0) for (const w of want) { idx=heads.findIndex(h=>h.toLowerCase().includes(w.toLowerCase())); if(idx>=0) break; }
             if(idx<0) return dflt;
             const tr=[...t.querySelectorAll('tbody tr')].find(x=>x.innerText.includes(rt));
             if(!tr) return dflt;
             const td=[...tr.querySelectorAll('td')][idx];
             return td ? td.innerText.trim() : dflt;
           }""", [row_text, want, default])
